### PR TITLE
ci: enable Dependabot for Go projects

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR configures Dependabot to run on this Go project.

cc @derberg

### CODE REVIEW

**Review by derberg — APPROVED** [review]
PRs from forks 😉

**Comment by smoya** [comment]
> PRs from forks 😉

I believed i was in a fork. Weird. closing, thanks for noticing.

**Comment by derberg** [comment]
@smoya no need to close, just reminder for future

**Comment by smoya** [comment]
> @smoya no need to close, just reminder for future

I prefer doing things in the best way as possible.

**Pull request closed without merging**
