### PR TITLE
fix: recursive dereferencing

### LINKED ISSUE #82: Recursive dereferencing is not working
#### Describe the bug
TL;DR: references of a reference are never dereferenced.

JSON references that refer to a value that contains references are not dereferenced recursively.

#### How to Reproduce

```go
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/asyncapi/parser-go/pkg/parser"
)

func main() {
	b := `
asyncapi: '2.0.0' # Go parser does not support 2.1.0 at this moment.
info:
  title: Dereferencing bug in parser-go
  version: 1.0.0
  description: This is demonstrates a bug in the parser-go package.
channels:
  test:
    publish:
      message:
        $ref: 'https://raw.githubusercontent.com/asyncapi/asyncapi/2.0.0/examples/2.0.0/streetlights.yml#/components/messages/lightMeasured'
`
	r, err := parser.NewReader(b)
	if err != nil {
		log.Fatal(err)
	}

	p, err := parser.New()
	if err != nil {
		log.Fatal(err)
	}

	w := bytes.NewBuffer(nil)
	if err := p(r, w); err != nil {
		log.Fatal(err)
	}

	fmt.Println(w.String())
}
```

```bash
2021/09/14 17:55:51 #/components/messageTraits/commonHeaders: key not found
#/components/schemas/lightMeasuredPayload: key not found
exit status 1
```

However, [parser-js](https://github.com/asyncapi/parser-go) works as expected as showed here https://github.com/asyncapi/event-gateway/pull/42#discussion_r708102756

#### Expected behavior
Referencing to a value with references should bring back all it's references which it depends on.
In the example, both `commonHeaders` and `lightMeasuredPayload` should be derefered correctly.

### PR DESCRIPTION
**Pull request by BuJo**
**Description**

* Local references of references were not dereferenced.

**Related issue(s)**

* Fixes #82

### CODE REVIEW

**Comment by BuJo** [comment]
I've added a test for this case.

**Review by smoya — APPROVED** [review]
LGTM! 🚀 🌔

**Comment by BuJo** [comment]
Thank you @smoya !

**Pull request merged**
